name: 교육연구원 자료 업데이트

on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행
  workflow_dispatch:  # 수동으로 실행할 수도 있음

jobs:
  update-materials:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 필요한 패키지 설치
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: 자료 크롤링 및 업데이트
        run: python scripts/update_materials.py

      - name: 변경사항 커밋
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/all_materials.json
          git diff --quiet && git diff --staged --quiet || git commit -m "자동 업데이트: 교육연구원 자료 추가"
          git push
